name: VoxelMap
version: ${version}
main: com.mamiyaotaru.voxelmap.paper.VoxelmapPaperPlugin
description: Sends server-side VoxelMap settings to VoxelMap clients
api-version: '1.14'
commands:
  voxelmap:
    description: Reloads the VoxelMap server settings
    usage: /voxelmap reload
    permission: voxelmap.reload
permissions:
  voxelmap.reload:
    description: Allows reloading the VoxelMap server settings
    default: op
